#!/usr/bin/env bash
#Displays numbers from 1 to 10 in addition to:
#  "bad luck from China for the 4th loop iteration
#  "bad luck from Japan for the 9th loop iteration
#  "bad luck from Italy for the 17th loop iteration

counter=1
while [ $counter -le 20 ]
do
    echo "$counter"
    case $counter in
        4)
            echo "$i: Bad luck from China"
            ;;
        9)
            echo "$i: Bad luck from Japan"
            ;;
        17)
            echo "$i: Bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
    i=$((i+1))
done
