#!/usr/bin/env bash
#Displays numbers from 1 to 10 in addition to:
#  "bad luck from China for the 4th loop iteration
#  "bad luck from Japan for the 9th loop iteration
#  "bad luck from Italy for the 17th loop iteration

counter=1
while [ $counter -le 20 ]
do
    case $counter in
	    "4") echo "Bad luck from China";;
	    "9") echo "Bad luck from Japan";;
	    "17") echo "Bad luck from Italy";;
	    *)
	    echo $counter
    esac
    ((counter++))
done
